extend = "../Makefile.toml"

[env]
NAME = { value = "Test Arbitrum Stylus Token", condition = { env_not_set = ["NAME"] } }
SYMBOL = { value = "SMB", condition = { env_not_set = ["SYMBOL"] } }

[tasks.wasm]
private = false
extend = "stylus-wasm"

[tasks.dist]
dependencies = ["wasm"]
